### ISSUE TITLE
How to run a GUI version of Maya ?

### ISSUE THREAD

**Issue by tupipa** [mottosso/docker-maya#4]
Hi, I try to run Maya with GUI inside container.

I build the container and install maya with the .tgz ball downloaded from the official autodesk website.

Here is the Dockerfile and the way I run the containers: https://gist.github.com/tupipa/6c1443b043c090e75a766b6b114cf9ff

The setup GUI running inside Docker container showed installation was sucessful. But when I run maya, just nothing happens.

Could you help to find out what is missing in my settings?

Thanks

**Comment by tupipa** [comment]
The way I run container with GUI is 
docker run -it \
    --net host \
    -e DISPLAY=$DISPLAY \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $(pwd)/root/workdir:/root/workdir \
    --device /dev/snd \
    -v /dev/shm:/dev/shm \
    --name=maya \
    tupipa/maya

It's based on this blog post: https://blog.jessfraz.com/post/docker-containers-on-the-desktop/

**Comment by mottosso** [comment]
Hey @tupipa, honestly I'm not sure as I've never tried this with Maya.

Have you tried something simpler, like `glxgears`? Odds are there are some underlying issues unrelated to Maya, and running this first would get you to the point where you can get an OpenGL window up on your local machine.

Also see this discussion: https://groups.google.com/forum/#!topic/docker-user/7w97EtTzZLU

**Comment by willjp** [comment]
Hey guys!

If it's helpful, I've been able to get maya-GUI to run within a docker container by installing the same family of video-drivers within the container as on the host-system (but I have not tested mayagui extensively, and I have only tested it using the mesa drivers)

This link was very helpful for me: http://gernotklingler.com/blog/howto-get-hardware-accelerated-opengl-support-docker/


## host-system
``` yaml
os: Archlinux
video-driver-packages:
   - mesa
   - lib32-mesa
```

## container
``` yaml
os:  Centos7.2   (latest officially supported by maya2017)
video-driver-packages:
   - mesa-libGLU
   - mesa-dri-drivers
```

You'll also want to install an X-server within the container. I might
have gone a little overboard on the packages here, sorry:

``` yaml
maya dependencies:
   - libXp
   - libtiff
   - compat-libtiff3
   - libpng12
   - gamin
   - libXcomposite
   - libXinerama
   - libXrandr
   - libxslt
   - pulseaudio-libs
   - redhat-lsb
   - xorg-x11-fonts-ISO8859-1-100dpi
   - xorg-x11-fonts-ISO8859-1-75dpi
   - xorg-x11-fonts-75dpi
   - xorg-x11-fonts-100dpi

X11 dependencies:
   - xorg-x11-server-Xorg
   - xorg-x11-xauth

test your Xorg:
   - xeyes
   - glxgears
```

## Docker Build Command
``` sh
docker run                                   \
   --hostname dockermaya                     \
                                             \
   `# X11 sharing`                           \
   -v /tmp/.X11-unix/X0:/tmp/.X11-unix/X0:rw \
   -e DISPLAY=unix$DISPLAY                   \
   --device=/dev/dri:/dev/dri                \
                                             \
   `# maya-environment (thanks mottoso!!)`   \
   -e MAYA_DISABLE_CIP=1                     \
   -ti
```
